package com.campustagram.core.security.enums;

public enum PermissionType {
	PERMISSION_VIEW ,
	PERMISSION_EDIT ,
	PERMISSION_ADD ,
	PERMISSION_REMOVE ,
	PERMISSION_BLOCK ,
	PERMISSION_UNBLOCK ,
	PERMISSION_MAINTENANCE ,
	PERMISSION_SYSTEM_NOTIFICATION ,
	PERMISSION_SYSTEM_INFO_COPY ,
	PERMISSION_TICKET_OPEN ,
	PERMISSION_TICKET_ANSWER ,
	PERMISSION_VIEW_PROCESS_LOGS ,
	PERMISSION_VIEW_PAGE_VISIT_LOGS
}