package com.campustagram.core.security.enums;

public enum RoleType {
	ROLE_USER_MANAGEMENT ,
	ROLE_ROLE_MANAGEMENT ,
	ROLE_NOTIFICATION_MANAGEMENT ,
	ROLE_LOG_MANAGEMENT ,
	ROLE_SUPPORT_MANAGEMENT ,
	ROLE_SYSTEM_MANAGEMENT ,
	ROLE_SYSTEM_LOG_MANAGEMENT ,
	ROLE_SYSTEM_SETTINGS_MANAGEMENT ,
	ROLE_SYSTEM_EMAIL_MANAGEMENT ,
	ROLE_SYSTEM_PROXY_LIST_MANAGEMENT ,
	ROLE_SYSTEM_PROXY_GROUP_MANAGEMENT ,
	ROLE_SYSTEM_PROXY_CHECK_MANAGEMENT ,
	ROLE_SYSTEM_USER_AGENT_MANAGEMENT ,
	ROLE_SYSTEM_DB_MANAGEMENT ,
	ROLE_SYSTEM_PERFORMANCE_MANAGEMENT ,
	ROLE_SYSTEM_PERFORMANCE_CPU_MANAGEMENT ,
	ROLE_SYSTEM_PERFORMANCE_MEMORY_MANAGEMENT ,
	ROLE_SYSTEM_PERFORMANCE_DISC_MANAGEMENT ,
	ROLE_SYSTEM_DOCUMENTATION_MANAGEMENT ,	
}